using System;

namespace Ex_6._2
{
    class Program
    {
        static void Main(string[] args)
        {   double n1, n2;
            Console.ForegroundColor = ConsoleColor.Black;
            Console.BackgroundColor = ConsoleColor.Gray;
            Console.SetCursorPosition(25,2);
            Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ CALCULADORA ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
            Console.SetCursorPosition(25,3);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,4);
            Console.Write("░░          Seja bem vindo(a), selecione a operação que deseja:           ░░");
            Console.SetCursorPosition(25,5);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,6);
            Console.Write("░░      [1] Adição   [2] Subtração   [3] Divisão  [4] Multiplicação       ░░");
            Console.SetCursorPosition(25,7);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,8);
            Console.Write("░░                          Sua escolha é: [ ]                            ░░");
            Console.SetCursorPosition(25,9);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,10);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,11);
            Console.Write("░░                                                                        ░░");
            Console.SetCursorPosition(25,12);
            Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
            Console.SetCursorPosition(69,8);
            Console.ForegroundColor = ConsoleColor.DarkRed;
            int escolha = Convert.ToInt32(Console.ReadLine());
            switch (escolha) {
                case 1:
                    Console.BackgroundColor = ConsoleColor.White;
                    Console.Clear();
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(25,2);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ADIÇÃO ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.SetCursorPosition(25,3);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,4);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,5);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,6);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,7);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,8);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,9);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,10);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,11);
                    Console.Write("▓▓                                      ▓▓");
                    Console.SetCursorPosition(25,12);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(28,6);
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n1 = Convert.ToDouble(Console.ReadLine());
                    Console.SetCursorPosition(28,7);
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n2 = Convert.ToDouble(Console.ReadLine());
                    double soma = n1 + n2;
                    Console.SetCursorPosition(28,9);
                    Console.Write("A soma dos números é igual a: "+soma);
                    Console.ReadKey();
                    break;
                case 2:
                    Console.BackgroundColor = ConsoleColor.White;
                    Console.Clear();
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(25,2);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ SUBTRAÇÃO ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.SetCursorPosition(25,3);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,4);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,5);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,6);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,7);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,8);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,9);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,10);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,11);
                    Console.Write("▓▓                                         ▓▓");
                    Console.SetCursorPosition(25,12);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(28,6);
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n1 = Convert.ToDouble(Console.ReadLine());
                    Console.SetCursorPosition(28,7);
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n2 = Convert.ToDouble(Console.ReadLine());
                    double sub = n1 - n2;
                    Console.SetCursorPosition(28,9);
                    Console.Write("A subtração dos números é igual a: "+sub);
                    Console.ReadKey();
                    break;
                case 3:
                   Console.BackgroundColor = ConsoleColor.White;
                    Console.Clear();
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(25,2);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ DIVISÃO ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.SetCursorPosition(25,3);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,4);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,5);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,6);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,7);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,8);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,9);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,10);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,11);
                    Console.Write("▓▓                                       ▓▓");
                    Console.SetCursorPosition(25,12);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(28,6);
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n1 = Convert.ToDouble(Console.ReadLine());
                    Console.SetCursorPosition(28,7);
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n2 = Convert.ToDouble(Console.ReadLine());
                    double div = n1 / n2;
                    Console.SetCursorPosition(28,9);
                    Console.Write("A divisão dos números é igual a: "+div);
                    Console.ReadKey();
                    break;
                case 4:
                    Console.BackgroundColor = ConsoleColor.White;
                    Console.Clear();
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(25,2);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ MULTIPLICAÇÃO ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.SetCursorPosition(25,3);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,4);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,5);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,6);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,7);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,8);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,9);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,10);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,11);
                    Console.Write("▓▓                                             ▓▓");
                    Console.SetCursorPosition(25,12);
                    Console.Write("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓");
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.SetCursorPosition(28,6);
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n1 = Convert.ToDouble(Console.ReadLine());
                    Console.SetCursorPosition(28,7);
                    Console.ForegroundColor = ConsoleColor.Black;
                    Console.Write("Digite um número: ");
                    Console.ForegroundColor = ConsoleColor.DarkGray;
                    n2 = Convert.ToDouble(Console.ReadLine());
                    double mult = n1 * n2;
                    Console.SetCursorPosition(28,9);
                    Console.Write("A multiplicação dos números é igual a: "+mult);
                    Console.ReadKey();
                    break;
                default:
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.SetCursorPosition (49,10);
                    Console.Write("Selecione uma opção válida!");
                    Console.ReadKey();
                    break;            
                 }
        }
    }
}
