using System;

namespace Ex_6._3
{
    class Program
    {
        static void Main(string[] args)
        {   
            double sal, dif, newsal;
            Console.ForegroundColor = ConsoleColor.DarkGray;
            Console.BackgroundColor = ConsoleColor.White;
            Console.SetCursorPosition(25,2);
            Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
            Console.SetCursorPosition(25,3);
            Console.Write("░░                       ░░ AUMENTO DE SALÁRIO ░░                      ░░");
            Console.SetCursorPosition(25,4);
            Console.Write("░░                       ░░░░░░░░░░░░░░░░░░░░░░░░                      ░░");
            Console.SetCursorPosition(25,5);
            Console.Write("░░                                                                     ░░");
            Console.SetCursorPosition(25,6);
            Console.Write("░░                       Selecione o seu cargo:                        ░░");
            Console.SetCursorPosition(25,7);
            Console.Write("░░                                                                     ░░");
            Console.SetCursorPosition(25,8);
            Console.Write("░░        [1] Gerente   [2] Analista   [3] Técnico  [4] Outro          ░░");
            Console.SetCursorPosition(25,9);
            Console.Write("░░                                                                     ░░");
            Console.SetCursorPosition(25,10);
            Console.Write("░░                         Sua escolha é: [ ]                          ░░");
            Console.SetCursorPosition(25,11);
            Console.Write("░░                                                                     ░░");
            Console.SetCursorPosition(25,12);
            Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
            Console.SetCursorPosition(68,10);
            Console.ForegroundColor = ConsoleColor.Black;
            int escolha = Convert.ToInt32(Console.ReadLine());
            switch (escolha) {
                case 1:
                        Console.BackgroundColor = ConsoleColor.Black;
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.DarkBlue;
                        Console.BackgroundColor = ConsoleColor.White;
                        Console.SetCursorPosition(25,2);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(25,3);
                        Console.Write("░░                       ░░ GERENTE ░░                      ░░");
                        Console.SetCursorPosition(25,4);
                        Console.Write("░░                       ░░░░░░░░░░░░░                      ░░");
                        Console.SetCursorPosition(25,5);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,6);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,7);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,8);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,9);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,10);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,11);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,12);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(68,10);
                        Console.ForegroundColor = ConsoleColor.DarkBlue;
                        Console.SetCursorPosition(28,6);
                        Console.Write("Digite seu salário: R$");
                        sal = Convert.ToDouble(Console.ReadLine());
                        dif = sal * 0.10;
                        newsal = sal + dif;
                        Console.ForegroundColor = ConsoleColor.Black;
                        Console.SetCursorPosition(28,8);
                        Console.Write("Salário Antigo: R$"+sal);
                        Console.SetCursorPosition(28,9);
                        Console.Write("Aumento de: +R$"+dif);
                        Console.SetCursorPosition(28,10);
                        Console.Write("Novo Salário: R$"+newsal);
                        Console.ReadKey();
                    break;
                case 2:
                        Console.BackgroundColor = ConsoleColor.Black;
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.DarkGreen;
                        Console.BackgroundColor = ConsoleColor.White;
                        Console.SetCursorPosition(25,2);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(25,3);
                        Console.Write("░░                       ░░ ANALISTA ░░                      ░░");
                        Console.SetCursorPosition(25,4);
                        Console.Write("░░                       ░░░░░░░░░░░░░░                      ░░");
                        Console.SetCursorPosition(25,5);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,6);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,7);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,8);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,9);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,10);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,11);
                        Console.Write("░░                                                           ░░");
                        Console.SetCursorPosition(25,12);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(68,10);
                        Console.ForegroundColor = ConsoleColor.DarkGreen;
                        Console.SetCursorPosition(28,6);
                        Console.Write("Digite seu salário: R$");
                        sal = Convert.ToDouble(Console.ReadLine());
                        dif = sal * 0.20;
                        newsal = sal + dif;
                        Console.ForegroundColor = ConsoleColor.Black;
                        Console.SetCursorPosition(28,8);
                        Console.Write("Salário Antigo: R$"+sal);
                        Console.SetCursorPosition(28,9);
                        Console.Write("Aumento de: +R$"+dif);
                        Console.SetCursorPosition(28,10);
                        Console.Write("Novo Salário: R$"+newsal);
                        Console.ReadKey();
                    break;
                case 3:
                    Console.BackgroundColor = ConsoleColor.Black;
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.DarkRed;
                        Console.BackgroundColor = ConsoleColor.White;
                        Console.SetCursorPosition(25,2);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(25,3);
                        Console.Write("░░                       ░░ TÉCNICO ░░                      ░░");
                        Console.SetCursorPosition(25,4);
                        Console.Write("░░                       ░░░░░░░░░░░░░                      ░░");
                        Console.SetCursorPosition(25,5);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,6);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,7);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,8);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,9);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,10);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,11);
                        Console.Write("░░                                                          ░░");
                        Console.SetCursorPosition(25,12);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(68,10);
                        Console.ForegroundColor = ConsoleColor.DarkRed;
                        Console.SetCursorPosition(28,6);
                        Console.Write("Digite seu salário: R$");
                        sal = Convert.ToDouble(Console.ReadLine());
                        dif = sal * 0.30;
                        newsal = sal + dif;
                        Console.ForegroundColor = ConsoleColor.Black;
                        Console.SetCursorPosition(28,8);
                        Console.Write("Salário Antigo: R$"+sal);
                        Console.SetCursorPosition(28,9);
                        Console.Write("Aumento de: +R$"+dif);
                        Console.SetCursorPosition(28,10);
                        Console.Write("Novo Salário: R$"+newsal);
                        Console.ReadKey();
                    break;
                default:
                        Console.BackgroundColor = ConsoleColor.Black;
                        Console.Clear();
                        Console.ForegroundColor = ConsoleColor.DarkMagenta;
                        Console.BackgroundColor = ConsoleColor.White;
                        Console.SetCursorPosition(25,2);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(25,3);
                        Console.Write("░░                       ░░ OUTROS ░░                      ░░");
                        Console.SetCursorPosition(25,4);
                        Console.Write("░░                       ░░░░░░░░░░░░                      ░░");
                        Console.SetCursorPosition(25,5);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,6);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,7);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,8);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,9);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,10);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,11);
                        Console.Write("░░                                                         ░░");
                        Console.SetCursorPosition(25,12);
                        Console.Write("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
                        Console.SetCursorPosition(68,10);
                        Console.ForegroundColor = ConsoleColor.DarkMagenta;
                        Console.SetCursorPosition(28,6);
                        Console.Write("Digite seu salário: R$");
                        sal = Convert.ToDouble(Console.ReadLine());
                        dif = sal * 0.40;
                        newsal = sal + dif;
                        Console.ForegroundColor = ConsoleColor.Black;
                        Console.SetCursorPosition(28,8);
                        Console.Write("Salário Antigo: R$"+sal);
                        Console.SetCursorPosition(28,9);
                        Console.Write("Aumento de: +R$"+dif);
                        Console.SetCursorPosition(28,10);
                        Console.Write("Novo Salário: R$"+newsal);
                        Console.ReadKey();
                    break;            
            }

            
        }
    }
}